rotary_motor_model_dict = {1: ['motor_type', 'one', 1.0, 'float32', 'N', '', '电机类型'],
                           2: ['R0', 'one', 0.5, 'float32', 'N', '', ''],
                           3: ['TCR', 'one', 0.004, 'float32', 'N', '', ''],
                           4: ['Ld', 'one', 0.01, 'float32', 'N', '', ''],
                           5: ['Lq', 'one', 0.01, 'float32', 'N', '', ''],
                           6: ['kF', 'one', 0.1, 'float32', 'N', '', '力常数'],
                           7: ['mass', 'one', 0.1, 'float32', 'N', '', '质量或惯量'],
                           8: ['friction', 'one', 0.0, 'float32', 'N', '', '静摩擦'],
                           9: ['damp', 'one', 0.0001, 'float32', 'N', '', '阻尼'],
                           10: ['Pn', 'one', 1.0, 'float32', 'N', '', '极对数'],
                           11: ['pole_pitch_mm', 'one', 32.0, 'float32', 'N', '', '极距'],
                           12: ['Ua', 'one', 0.0, 'float32', 'N', '', ''],
                           13: ['Ub', 'one', 0.0, 'float32', 'N', '', ''],
                           14: ['enable', 'one', 0.0, 'float32', 'N', '', ''],
                           15: ['current_noise_amp', 'one', 0.1, 'float32', 'N', '', '力传感器噪声幅值'],
                           16: ['Iu', 'one', 0.0, 'float32', 'N', '', 'U相电流'],
                           17: ['Iv', 'one', 0.0, 'float32', 'N', '', 'V相电流'],
                           18: ['Iw', 'one', 0.0, 'float32', 'N', '', 'W相电流'],
                           19: ['encoder_type', 'one', 0.0, 'float32', 'N', '', '编码器类型'],
                           20: ['dpi_um', 'one', 1.0, 'float32', 'N', '', '光栅分辨率'],
                           21: ['pole_pitch_mm', 'one', 40.0, 'float32', 'N', '', '极距'],
                           22: ['lines', 'one', 4096.0, 'float32', 'N', '', '编码器线数'],
                           23: ['direction', 'one', 1.0, 'float32', 'N', '', '方向'],
                           24: ['offset', 'one', 0.0, 'float32', 'N', '', '补偿'],
                           25: ['enc_pos', 'one', 0.0, 'float32', 'N', '', '位置'],
                           26: ['enc_pos_sum', 's', 0.0, 'float32', 'N', '', ''],
                           27: ['dt', 's', 5e-05, 'float32', 'N', '', 'dt'],
                           28: ['g', 'N/kg', 9.8, 'float32', 'N', '', '重力加速度'],
                           29: ['tilt_angle', 'None', 0.0, 'float32', 'N', '', '倾斜角度'],
                           30: ['mouse_type', 'N/m', 0.0, 'float32', 'N', '', '鼠标类型'],
                           31: ['type', 'N/m', 0.0, 'float32', 'N', '', '弹簧类型'],
                           32: ['stiff', 'N/(m/s)', 0.0, 'float32', 'N', '', '回复弹簧刚度系数'],
                           33: ['damp', 'm', 0.0, 'float32', 'N', '', '减幅'],
                           34: ['pos_mm', 'N', 0.0, 'float32', 'N', '', '弹簧放置的位置'],
                           35: ['force', 'one', 0.0, 'float32', 'N', '', '弹簧受力'],
                           36: ['arm_length_mm', 'one', 0.0, 'float32', 'N', '', '关节上旋转臂长'],
                           37: ['x_mm', 'one', 0.0, 'float32', 'N', '', '基点偏移_x'],
                           38: ['y_mm', 'one', 0.0, 'float32', 'N', '', '基点偏移_y'],
                           39: ['click_flag', 'one', 0.0, 'float32', 'N', '', 'click_flag'],
                           40: ['sd2cnt', 'one', 0.0, 'float32', 'N', '', ''],
                           }
data_model_dict_load = {'rotary_motor_model_dict': rotary_motor_model_dict
                        }
